#!/bin/bash

# A Bash Script to install Docker and on Ubuntu



sudo apt install -y apt-transport-https ca-certificates curl software-properties-common


curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

sudo apt update

sudo snap install docker

sudo docker run hello-world

